// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/boernd/tex-operator/pkg/apis/tex/v1alpha1.TexService":       schema_pkg_apis_tex_v1alpha1_TexService(ref),
		"github.com/boernd/tex-operator/pkg/apis/tex/v1alpha1.TexServiceSpec":   schema_pkg_apis_tex_v1alpha1_TexServiceSpec(ref),
		"github.com/boernd/tex-operator/pkg/apis/tex/v1alpha1.TexServiceStatus": schema_pkg_apis_tex_v1alpha1_TexServiceStatus(ref),
	}
}

func schema_pkg_apis_tex_v1alpha1_TexService(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TexService is the Schema for the texservices API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/boernd/tex-operator/pkg/apis/tex/v1alpha1.TexServiceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/boernd/tex-operator/pkg/apis/tex/v1alpha1.TexServiceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/boernd/tex-operator/pkg/apis/tex/v1alpha1.TexServiceSpec", "github.com/boernd/tex-operator/pkg/apis/tex/v1alpha1.TexServiceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tex_v1alpha1_TexServiceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TexServiceSpec defines the desired state of TexService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_tex_v1alpha1_TexServiceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TexServiceStatus defines the observed state of TexService",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
