apiVersion: apps/v1
kind: Deployment
metadata:
  name: tex-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tex-operator
  template:
    metadata:
      labels:
        name: tex-operator
    spec:
      serviceAccountName: tex-operator
      containers:
        - name: tex-operator
          image: infonova/tex-operator:latest
          command:
          - tex-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "tex-operator"
